
#!/bin/ash

echo running: /bin/rqlite-recover -c -app $APP_NAME -l $LOG_LEVEL -t $UPDATE_INTERVAL_SECONDS -d $SHARED_STORAGE_FOLDER -n $NODE_HOSTNAME -http $RQLITE_HTTP_PORT -raft $RQLITE_RAFT_PORT -timeout $READINESS_TIMEOUT_MIN
/bin/rqlite-recover -c -app $APP_NAME -l $LOG_LEVEL -t $UPDATE_INTERVAL_SECONDS -d $SHARED_STORAGE_FOLDER -n $NODE_HOSTNAME -http $RQLITE_HTTP_PORT -raft $RQLITE_RAFT_PORT -timeout $READINESS_TIMEOUT_MIN